# Generated by Django 6.0.2 on 2026-03-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restructure_manager_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dnd_enabled',
            field=models.BooleanField(default=False, help_text='Do Not Disturb — suppress notifications.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dnd_end',
            field=models.TimeField(blank=True, help_text='DND quiet hours end time.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dnd_start',
            field=models.TimeField(blank=True, help_text='DND quiet hours start time.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, default='en', help_text='Preferred UI language code (e.g. en, ms, zh).', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.TextField(blank=True, help_text='Personal signature appended to ticket replies.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', help_text="Agent's preferred timezone (e.g. Asia/Kuala_Lumpur).", max_length=50),
        ),
    ]
