# Generated by Django 6.0.2 on 2026-03-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_profile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_format',
            field=models.CharField(blank=True, default='YYYY-MM-DD', help_text='Preferred date display format.', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='density',
            field=models.CharField(blank=True, default='comfortable', help_text='List density: comfortable or compact.', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='sidebar_collapsed',
            field=models.BooleanField(default=False, help_text='Whether the sidebar defaults to collapsed.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(blank=True, default='system', help_text='UI theme: light, dark, or system.', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_format',
            field=models.CharField(blank=True, default='24h', help_text='Time format: 12h or 24h.', max_length=5),
        ),
    ]
