# Generated by Django 6.0.2 on 2026-05-07 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_auth_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='temporary_role',
            field=models.ForeignKey(blank=True, help_text='Role temporarily granted by an admin; overrides role until expiry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_members', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='temporary_role_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='temporary_role_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='temporary_role_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_grants_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
