# Generated by Django 6.0.2 on 2026-05-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_temporary_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='temporary_permissions',
            field=models.ManyToManyField(blank=True, help_text="Optional allow-list applied while a temporary role is active. When non-empty, the effective permission set is the intersection of the temporary role's permissions and this set. When empty, the temporary role's full permission set applies.", related_name='temporary_grants', to='accounts.permission'),
        ),
    ]
