# Generated by Django 6.0.2 on 2026-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_service_account',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
