# Generated by Django 6.0.2 on 2026-05-12 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usergroup'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='source_group',
            field=models.ForeignKey(blank=True, help_text="The UserGroup this conversation was seeded from. Used to deduplicate per-creator group conversations and to surface the group's name in the messaging UI.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='accounts.usergroup'),
        ),
    ]
