# Generated by Django 6.0.2 on 2026-02-06 04:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('ticket', 'Ticket'), ('contact', 'Contact'), ('company', 'Company')], help_text='The entity type this field belongs to.', max_length=50)),
                ('name', models.CharField(help_text='Human-readable field label.', max_length=100)),
                ('slug', models.SlugField(help_text='Machine-readable identifier; used as key in custom_data JSON.', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('checkbox', 'Checkbox'), ('file', 'File')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='For select/multiselect: [{"value": "...", "label": "..."}].')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this field is mandatory when saving the entity.')),
                ('default_value', models.JSONField(blank=True, help_text='Default value applied when the field is left empty.', null=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation constraints: {"min_length": 3, "max_length": 500, "min": 0, "max": 100, "regex": "..."}.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the module (lower = first).')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive fields are hidden from forms but data is retained.')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('visible_to_roles', models.ManyToManyField(blank=True, help_text='Roles that can see this field. Empty = visible to all.', related_name='visible_custom_fields', to='accounts.role')),
            ],
            options={
                'verbose_name': 'custom field definition',
                'verbose_name_plural': 'custom field definitions',
                'ordering': ['module', 'order'],
                'unique_together': {('tenant', 'module', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('value_text', models.TextField(blank=True, help_text='Stores text, textarea, select, multiselect, and file values.', null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, help_text='Stores number field values.', max_digits=20, null=True)),
                ('value_date', models.DateTimeField(blank=True, help_text='Stores date field values.', null=True)),
                ('value_bool', models.BooleanField(blank=True, help_text='Stores checkbox field values.', null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='custom_fields.customfielddefinition')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'custom field value',
                'verbose_name_plural': 'custom field values',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'field', 'value_text'], name='cfv_tenant_field_text'), models.Index(fields=['tenant', 'field', 'value_number'], name='cfv_tenant_field_number'), models.Index(fields=['tenant', 'field', 'value_date'], name='cfv_tenant_field_date')],
                'unique_together': {('field', 'content_type', 'object_id')},
            },
        ),
    ]
