# Generated by Django 6.0.2 on 2026-04-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_call_recording',
            field=models.BooleanField(default=False, help_text='Whether call recording is available on this plan.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_voip',
            field=models.BooleanField(default=False, help_text='Whether VoIP telephony is available on this plan.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_calls_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Monthly call limit.  NULL = unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='usagetracker',
            name='calls_made',
            field=models.PositiveIntegerField(default=0, help_text='VoIP calls made in the current billing period.'),
        ),
    ]
