# Generated by Django 6.0.2 on 2026-02-06 04:05

import apps.attachments.services
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('file', models.FileField(upload_to=apps.attachments.services.upload_path)),
                ('original_name', models.CharField(help_text='Original filename as uploaded by the user.', max_length=255)),
                ('mime_type', models.CharField(help_text='MIME type detected via python-magic (not from the client).', max_length=100)),
                ('size_bytes', models.PositiveIntegerField(help_text='File size in bytes.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='attachment_ct_obj_idx')],
            },
        ),
    ]
