# Generated by Django 6.0.2 on 2026-04-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_bouncing',
            field=models.BooleanField(db_index=True, default=False, help_text="Set True when a hard bounce is detected for this contact's email."),
        ),
    ]
