# Generated by Django 6.0.2 on 2026-04-05 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_add_email_bouncing'),
        ('tenants', '0006_add_auto_transition_on_assign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the most recent contact event (auto-updated).', null=True),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('mrr', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly recurring revenue.', max_digits=12, null=True)),
                ('health_score', models.PositiveSmallIntegerField(default=50, help_text='Account health score (0-100).')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(blank=True, help_text='CRM account this contact belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.account'),
        ),
        migrations.CreateModel(
            name='ContactEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(help_text='Type of event (e.g. created, assigned, status_changed, commented).', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('ticket', 'Ticket'), ('activity', 'Activity'), ('email', 'Email'), ('manual', 'Manual')], max_length=20)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_events', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contacts.contact')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'contact event',
                'verbose_name_plural': 'contact events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['contact', 'occurred_at'], name='contactevent_contact_occurred'), models.Index(fields=['tenant', 'source'], name='contactevent_tenant_source')],
            },
        ),
    ]
