# Generated by Django 6.0.2 on 2026-04-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_add_contact_to_ticketactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lead_score',
            field=models.PositiveSmallIntegerField(default=50, help_text='Lead score (0-100), calculated nightly.'),
        ),
    ]
