# Generated by Django 6.0.2 on 2026-04-15 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
        ('tenants', '0006_add_auto_transition_on_assign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='emoji',
            field=models.CharField(blank=True, default='', help_text='Custom emoji icon for the post.', max_length=10),
        ),
        migrations.AddField(
            model_name='newspost',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-hide after this time.', null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Highlight as urgent/breaking news.'),
        ),
        migrations.CreateModel(
            name='NewsPostReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction', models.CharField(choices=[('thumbs_up', '👍'), ('celebration', '🎉'), ('heart', '❤️'), ('rocket', '🚀'), ('eyes', '👀'), ('hundred', '💯')], max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='newsfeed.newspost')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'reaction'], name='newsfeed_ne_post_id_a3b7c1_idx')],
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='NewsPostRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='newsfeed.newspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
