# Generated by Django 6.0.2 on 2026-04-16 06:03

import apps.voip.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0004_contact_lead_score'),
        ('tenants', '0006_add_auto_transition_on_assign'),
        ('tickets', '0026_alter_ticketactivity_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asterisk_channel_id', models.CharField(blank=True, db_index=True, default='', help_text='Asterisk channel unique ID for ARI correlation.', max_length=255)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], max_length=10)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('answered', 'Answered'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('failed', 'Failed'), ('missed', 'Missed'), ('busy', 'Busy'), ('no_answer', 'No Answer'), ('voicemail', 'Voicemail')], default='ringing', max_length=20)),
                ('caller_number', models.CharField(max_length=50)),
                ('callee_number', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(help_text='When the call was initiated.')),
                ('answered_at', models.DateTimeField(blank=True, help_text='When the call was answered.', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the call ended.', null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Total call duration in seconds.')),
                ('hold_duration_seconds', models.PositiveIntegerField(default=0, help_text='Total time on hold in seconds.')),
                ('notes', models.TextField(blank=True, default='', help_text='Agent notes about the call.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Raw ARI event data and additional context.')),
                ('contact', models.ForeignKey(blank=True, help_text='Linked contact for CRM timeline.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='contacts.contact')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('ticket', models.ForeignKey(blank=True, help_text='Linked ticket for timeline logging.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.voip.models.recording_upload_path)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(default='audio/wav', max_length=50)),
                ('call_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='voip.calllog')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extension_number', models.CharField(help_text='Internal extension number (e.g., 1001).', max_length=10)),
                ('sip_username', models.CharField(help_text='PJSIP endpoint username (globally unique).', max_length=100, unique=True)),
                ('sip_password', models.CharField(help_text='SIP registration password (stored encrypted).', max_length=255)),
                ('caller_id_name', models.CharField(blank=True, default='', help_text='Display name for outbound caller ID.', max_length=100)),
                ('caller_id_number', models.CharField(blank=True, default='', help_text='Phone number for outbound caller ID.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(blank=True, help_text='Last successful SIP registration timestamp.', null=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voip_extensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['extension_number'],
                'unique_together': {('tenant', 'extension_number'), ('tenant', 'user')},
            },
        ),
        migrations.AddField(
            model_name='calllog',
            name='callee_extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_calls', to='voip.extension'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='caller_extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_calls', to='voip.extension'),
        ),
        migrations.CreateModel(
            name='VoIPSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asterisk_host', models.CharField(default='127.0.0.1', help_text='Asterisk server hostname or IP.', max_length=255)),
                ('asterisk_ari_port', models.PositiveIntegerField(default=8088, help_text='Asterisk ARI HTTP port.')),
                ('asterisk_wss_port', models.PositiveIntegerField(default=8089, help_text='Asterisk PJSIP WebSocket (WSS) port for browser clients.')),
                ('ari_username', models.CharField(blank=True, default='', help_text='ARI application username.', max_length=100)),
                ('ari_password', models.CharField(blank=True, default='', help_text='ARI application password (stored encrypted).', max_length=255)),
                ('stun_server', models.CharField(default='stun:stun.l.google.com:19302', help_text='STUN server URI for WebRTC NAT traversal.', max_length=255)),
                ('turn_server', models.CharField(blank=True, default='', help_text='TURN server URI for WebRTC relay.', max_length=255)),
                ('turn_username', models.CharField(blank=True, default='', max_length=100)),
                ('turn_password', models.CharField(blank=True, default='', max_length=255)),
                ('default_caller_id', models.CharField(blank=True, default='', help_text='Default outbound caller ID for this tenant.', max_length=50)),
                ('pjsip_context', models.CharField(blank=True, default='', help_text='Asterisk PJSIP context for tenant isolation.', max_length=100)),
                ('recording_enabled', models.BooleanField(default=False, help_text='Whether call recording is enabled for this tenant.')),
                ('voicemail_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'VoIP settings',
                'verbose_name_plural': 'VoIP settings',
            },
        ),
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('strategy', models.CharField(choices=[('ringall', 'Ring All'), ('roundrobin', 'Round Robin'), ('leastrecent', 'Least Recent'), ('fewestcalls', 'Fewest Calls'), ('random', 'Random')], default='ringall', max_length=20)),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text='Seconds to ring before moving to next agent or voicemail.')),
                ('max_wait_seconds', models.PositiveIntegerField(default=300, help_text='Maximum wait time in queue before dropping.')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('members', models.ManyToManyField(blank=True, related_name='call_queues', to='voip.extension')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['tenant', 'started_at'], name='voip_calllo_tenant__2665e4_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['tenant', 'caller_extension'], name='voip_calllo_tenant__6dc349_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['tenant', 'contact'], name='voip_calllo_tenant__23fe4e_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['tenant', 'status'], name='voip_calllo_tenant__039c56_idx'),
        ),
        migrations.AddConstraint(
            model_name='voipsettings',
            constraint=models.UniqueConstraint(fields=('tenant',), name='unique_voip_settings_per_tenant'),
        ),
    ]
