# Generated by Django 6.0.2 on 2026-04-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voipsettings',
            name='asterisk_use_ssl',
            field=models.BooleanField(default=False, help_text='Use HTTPS/WSS for ARI connection (required if FreePBX has SSL enabled).'),
        ),
        migrations.AlterField(
            model_name='voipsettings',
            name='asterisk_ari_port',
            field=models.PositiveIntegerField(default=8088, help_text='Asterisk ARI HTTP port (8088 for HTTP, 8089 for HTTPS).'),
        ),
    ]
