# Generated by Django 6.0.2 on 2026-03-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, help_text='Optional file attachment (PDF, DOCX, etc.)', null=True, upload_to='tenants/knowledge/articles/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='article',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
