# Generated by Django 6.0.2 on 2026-04-06 05:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_date_format_profile_density_and_more'),
        ('knowledge', '0003_article_approval_workflow'),
        ('tenants', '0006_add_auto_transition_on_assign'),
        ('tickets', '0023_add_inbox_workflow_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KBRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_snapshot', models.TextField()),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KBSearchGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('agent', 'Agent'), ('portal', 'Portal')], max_length=20)),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='KBTicketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KBVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.BooleanField()),
                ('session_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='review_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Internal (agents only)'), ('public', 'Public')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='knowledge_a_search__682520_gin'),
        ),
        migrations.AddField(
            model_name='kbrevision',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='knowledge.article'),
        ),
        migrations.AddField(
            model_name='kbrevision',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_revisions', to='accounts.tenantmembership'),
        ),
        migrations.AddField(
            model_name='kbsearchgap',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kbticketlink',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_ticket_links', to='accounts.tenantmembership'),
        ),
        migrations.AddField(
            model_name='kbticketlink',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_links', to='knowledge.article'),
        ),
        migrations.AddField(
            model_name='kbticketlink',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_links', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='kbvote',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='knowledge.article'),
        ),
        migrations.AlterUniqueTogether(
            name='kbsearchgap',
            unique_together={('tenant', 'query', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='kbticketlink',
            unique_together={('ticket', 'article')},
        ),
        migrations.AlterUniqueTogether(
            name='kbvote',
            unique_together={('article', 'session_key')},
        ),
    ]
