# Generated by Django 6.0.2 on 2026-05-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usergroup'),
        ('knowledge', '0004_kbrevision_kbsearchgap_kbticketlink_kbvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='kb_articles', to='accounts.usergroup'),
        ),
    ]
