# Generated by Django 6.0.2 on 2026-02-06 04:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="Subdomain identifier (e.g. 'demo' for demo.localhost).", max_length=63, unique=True)),
                ('domain', models.CharField(blank=True, help_text="Optional custom domain (e.g. 'crm.acme.com').", max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tenants are denied access via middleware.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_method', models.CharField(choices=[('django', 'Django (email + password)'), ('sso', 'Single Sign-On only'), ('both', 'Django + SSO')], default='django', max_length=10)),
                ('sso_provider', models.CharField(blank=True, choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('okta', 'Okta'), ('custom', 'Custom OIDC')], max_length=20, null=True)),
                ('sso_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sso_client_secret', models.CharField(blank=True, help_text='Encrypted in production via application-level encryption.', max_length=255, null=True)),
                ('sso_authority_url', models.URLField(blank=True, null=True)),
                ('sso_scopes', models.CharField(default='openid email profile', max_length=500)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('primary_color', models.CharField(default='#0d6efd', help_text="Hex colour code for the tenant's primary brand colour.", max_length=7)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'tenant settings',
                'verbose_name_plural': 'tenant settings',
            },
        ),
    ]
