# Generated by Django 6.0.2 on 2026-02-19 05:13

import apps.tenants.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='business_days',
            field=models.JSONField(default=apps.tenants.models.default_business_days, help_text='ISO weekday integers (0=Mon, 6=Sun) that are business days.'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='business_hours_end',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Business hours end (tenant local time).'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='business_hours_start',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Business hours start (tenant local time).'),
        ),
    ]
