# Generated by Django 6.0.2 on 2026-03-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantsettings_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='inbound_email_address',
            field=models.EmailField(blank=True, help_text='Custom inbound email address for this tenant (e.g. support@acme.com).', max_length=254, null=True, unique=True),
        ),
    ]
