# Generated by Django 6.0.2 on 2026-04-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings_inbound_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='auto_close_days',
            field=models.PositiveIntegerField(default=5, help_text="Days after 'resolved' before auto-closing the ticket."),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='csat_delay_minutes',
            field=models.PositiveIntegerField(default=60, help_text="Minutes after 'resolved' before sending CSAT survey email."),
        ),
    ]
