# Generated by Django 6.0.2 on 2026-04-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_phase4_closure_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='auto_transition_on_assign',
            field=models.BooleanField(default=True, help_text='When True, assigning a ticket on the default (Open) status automatically transitions it to In Progress.'),
        ),
    ]
