# Generated by Django 6.0.2 on 2026-04-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_auto_transition_on_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='auto_send_ticket_created_email',
            field=models.BooleanField(default=True, help_text="When True, the ticket-created confirmation email is sent to the contact automatically the moment a ticket is created from an inbound email. When False, agents send it manually from the ticket page (button: 'Send confirmation email')."),
        ),
    ]
