# Generated by Django 6.0.2 on 2026-04-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenantsettings_auto_send_ticket_created_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='auto_assign_inbound_email_tickets',
            field=models.BooleanField(default=False, help_text='When True, tickets created from inbound customer emails are automatically assigned to an Agent (role hierarchy_level=30) using a load-then-fairness policy: the agent with the fewest open tickets wins, ties broken by least-recently-assigned. Offline agents are skipped. When False, email tickets land unassigned and admins/managers triage manually.'),
        ),
    ]
