# Generated by Django 6.0.2 on 2026-05-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenantsettings_auto_assign_inbound_email_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='inbox_hub_enabled',
            field=models.BooleanField(default=False, help_text='When True, inbound emails are parked in the Inbox Hub for agent triage instead of auto-creating a Ticket. Agents convert to a Ticket explicitly via the Hub UI. When False (default), the legacy auto-create-ticket flow runs unchanged.'),
        ),
    ]
