# Generated by Django 6.0.2 on 2026-06-05 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox_hub', '0001_initial'),
        ('tenants', '0009_tenantsettings_inbox_hub_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='inbox_hub_auto_assign',
            field=models.BooleanField(default=True, help_text='When True (default), the Inbox Hub auto-assigns each parked email to an online agent in its routed department using load + fairness. When no agent is online the email is held in the department queue and auto-assigned the moment an eligible agent comes online. Set False to leave all parked email for manual claim/assignment.'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='inbox_hub_default_department',
            field=models.ForeignKey(blank=True, help_text='Fallback department for parked emails that match no routing rule. When unset, unmatched email stays department-less and is visible to any agent with a department membership (triage safety valve).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox_hub.department'),
        ),
    ]
