# Generated by Django 6.0.2 on 2026-05-15 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_user_is_service_account'),
        ('tenants', '0008_tenantsettings_auto_assign_inbound_email_tickets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="User-facing label, e.g. 'Zapier Integration'.", max_length=120)),
                ('prefix', models.CharField(db_index=True, help_text='First ~20 chars of the cleartext key (the lookup target).', max_length=20)),
                ('hashed_key', models.CharField(help_text='SHA-512 hex digest of the full cleartext key.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_used_user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(help_text='Human admin who minted the key.', on_delete=django.db.models.deletion.PROTECT, related_name='api_keys_created', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role for permission inheritance.', on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='accounts.role')),
                ('service_user', models.OneToOneField(help_text='Hidden synthetic user this key authenticates as.', on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'name')},
                'indexes': [
                    models.Index(fields=['prefix'], name='api_keys_ap_prefix_idx'),
                    models.Index(fields=['tenant', 'is_active'], name='api_keys_ap_tenant__active_idx'),
                ],
            },
        ),
    ]
