# Generated by Django 6.0.2 on 2026-05-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apikey',
            new_name='api_keys_ap_prefix_fda2a7_idx',
            old_name='api_keys_ap_prefix_idx',
        ),
        migrations.RenameIndex(
            model_name='apikey',
            new_name='api_keys_ap_tenant__52dde3_idx',
            old_name='api_keys_ap_tenant__active_idx',
        ),
    ]
