# Generated by Django 6.0.2 on 2026-02-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('commented', 'Commented'), ('deleted', 'Deleted'), ('field_changed', 'Field Changed'), ('imported', 'Imported'), ('exported', 'Exported'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed')], max_length=50),
        ),
    ]
