# Generated by Django 6.0.2 on 2026-04-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_add_comment_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('commented', 'Commented'), ('deleted', 'Deleted'), ('field_changed', 'Field Changed'), ('imported', 'Imported'), ('exported', 'Exported'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed'), ('sla_updated', 'SLA Updated'), ('pipeline_stage_changed', 'Pipeline Stage Changed'), ('email_linked', 'Email Linked'), ('email_actioned', 'Email Actioned'), ('reminder_created', 'Reminder Created'), ('reminder_completed', 'Reminder Completed'), ('reminder_cancelled', 'Reminder Cancelled'), ('reminder_rescheduled', 'Reminder Rescheduled'), ('outbound_call_logged', 'Outbound Call Logged'), ('outbound_call_completed', 'Outbound Call Completed')], max_length=50),
        ),
    ]
