# Generated by Django 6.0.2 on 2026-05-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('commented', 'Commented'), ('deleted', 'Deleted'), ('field_changed', 'Field Changed'), ('imported', 'Imported'), ('exported', 'Exported'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed'), ('sla_updated', 'SLA Updated'), ('pipeline_stage_changed', 'Pipeline Stage Changed'), ('email_linked', 'Email Linked'), ('email_actioned', 'Email Actioned'), ('reminder_created', 'Reminder Created'), ('reminder_completed', 'Reminder Completed'), ('reminder_cancelled', 'Reminder Cancelled'), ('reminder_rescheduled', 'Reminder Rescheduled'), ('outbound_call_logged', 'Outbound Call Logged'), ('outbound_call_completed', 'Outbound Call Completed'), ('api_key_created', 'API Key Created'), ('api_key_regenerated', 'API Key Regenerated'), ('api_key_revoked', 'API Key Revoked'), ('email_received', 'Email Received (Hub)'), ('email_categorised', 'Email Categorised'), ('email_queued', 'Email Queued'), ('email_agent_assigned', 'Email Agent Assigned'), ('email_reassigned', 'Email Reassigned'), ('email_escalated', 'Email Escalated'), ('email_converted_to_ticket', 'Email Converted to Ticket'), ('email_dismissed', 'Email Dismissed')], max_length=50),
        ),
    ]
