# Generated by Django 6.0.2 on 2026-02-06 04:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('auto_assign', models.BooleanField(default=False)),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_queues', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'queue',
                'verbose_name_plural': 'queues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10)),
                ('first_response_minutes', models.PositiveIntegerField(help_text='Target time (in minutes) for the first agent response.')),
                ('resolution_minutes', models.PositiveIntegerField(help_text='Target time (in minutes) for full resolution.')),
                ('business_hours_only', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'SLA policy',
                'verbose_name_plural': 'SLA policies',
                'ordering': ['priority'],
                'unique_together': {('tenant', 'priority')},
            },
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('response_breach', 'Response SLA breach'), ('resolution_breach', 'Resolution SLA breach'), ('idle_time', 'Idle time exceeded')], max_length=20)),
                ('threshold_minutes', models.PositiveIntegerField(help_text='Minutes after trigger condition before this rule fires.')),
                ('action', models.CharField(choices=[('assign', 'Re-assign ticket'), ('notify', 'Send notification'), ('change_priority', 'Escalate priority')], max_length=20)),
                ('notify_message', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_targets', to='accounts.role')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_targets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('sla_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_rules', to='tickets.slapolicy')),
            ],
            options={
                'verbose_name': 'escalation rule',
                'verbose_name_plural': 'escalation rules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(editable=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Arbitrary key/value data for custom fields.')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='contacts.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='contacts.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.queue')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'ticket assignment',
                'verbose_name_plural': 'ticket assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('order', models.PositiveIntegerField()),
                ('is_closed', models.BooleanField(default=False, help_text='Marks this status as a resolution/closed state.')),
                ('is_default', models.BooleanField(default=False, help_text='If True, new tickets for this tenant receive this status.')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ticket status',
                'verbose_name_plural': 'ticket statuses',
                'ordering': ['order'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketstatus'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'status'], name='tickets_tic_tenant__e2638a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'assignee'], name='tickets_tic_tenant__755322_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'priority'], name='tickets_tic_tenant__c84d54_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant', 'created_at'], name='tickets_tic_tenant__ebb48d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('tenant', 'number')},
        ),
    ]
