# Generated by Django 6.0.2 on 2026-02-09 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent assignment.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='The user who last assigned this ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
