# Generated by Django 6.0.2 on 2026-02-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_assigned_at_ticket_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketactivity',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('commented', 'Commented'), ('internal_note', 'Internal Note'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('escalated', 'Escalated'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed')], max_length=50),
        ),
    ]
