# Generated by Django 6.0.2 on 2026-02-19 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantsettings_business_days_and_more'),
        ('tickets', '0005_ticketcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_responded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the first agent response (comment or assignment).', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_resolution_breached',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the resolution SLA was breached.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_response_breached',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the first-response SLA was breached.'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
    ]
