# Generated by Django 6.0.2 on 2026-03-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_cannedresponse_savedview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cannedresponse',
            new_name='tickets_can_tenant__e45d2f_idx',
            old_name='tickets_can_tenant__83e6de_idx',
        ),
        migrations.RenameIndex(
            model_name='cannedresponse',
            new_name='tickets_can_shortcu_b413e5_idx',
            old_name='tickets_can_shortcu_d9f3a5_idx',
        ),
        migrations.RenameIndex(
            model_name='savedview',
            new_name='tickets_sav_tenant__f04bbf_idx',
            old_name='tickets_sav_tenant__a1c2b3_idx',
        ),
    ]
