# Generated by Django 6.0.2 on 2026-03-26 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings_inbound_email_address'),
        ('tickets', '0008_rename_tickets_can_tenant__83e6de_idx_tickets_can_tenant__e45d2f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_counter', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ticket counter',
                'verbose_name_plural': 'ticket counters',
            },
        ),
    ]
