# Generated by Django 6.0.2 on 2026-03-29 11:28

import apps.tickets.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings_inbound_email_address'),
        ('tickets', '0010_seed_ticket_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstatus',
            name='pauses_sla',
            field=models.BooleanField(default=False, help_text='If True, SLA clocks pause while a ticket is in this status.'),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('commented', 'Commented'), ('internal_note', 'Internal Note'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('escalated', 'Escalated'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed'), ('sla_paused', 'SLA Paused'), ('sla_resumed', 'SLA Resumed')], max_length=50),
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(default='UTC', help_text="IANA timezone name (e.g. 'America/New_York').", max_length=50)),
                ('schedule', models.JSONField(default=apps.tickets.models.default_business_hours_schedule, help_text='Per-day open/close times. Keys are weekday ints 0–6 as strings.')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'business hours',
                'verbose_name_plural': 'business hours',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='unique_business_hours_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='The holiday date.')),
                ('name', models.CharField(help_text="Holiday name (e.g. 'Christmas Day').", max_length=200)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'public holiday',
                'verbose_name_plural': 'public holidays',
                'ordering': ['date'],
                'unique_together': {('tenant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SLAPause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paused_at', models.DateTimeField(help_text='When the SLA clock was paused.')),
                ('resumed_at', models.DateTimeField(blank=True, help_text='When the SLA clock was resumed. Null if still paused.', null=True)),
                ('reason', models.CharField(choices=[('waiting_on_customer', 'Waiting on customer'), ('manual', 'Manual pause')], default='waiting_on_customer', max_length=30)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_pauses', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'SLA pause',
                'verbose_name_plural': 'SLA pauses',
                'ordering': ['-paused_at'],
                'indexes': [models.Index(fields=['ticket', 'resumed_at'], name='slapause_ticket_resumed')],
            },
        ),
    ]
