# Generated by Django 6.0.2 on 2026-04-01 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticketstatus_pauses_sla_alter_ticketactivity_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('portal', 'Portal'), ('agent', 'Agent'), ('chat', 'Chat')], default='agent', help_text='Intake channel that created this ticket.', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent escalation.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalation_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this ticket has been escalated.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_first_response_due',
            field=models.DateTimeField(blank=True, help_text='UTC deadline for first agent response.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_paused_at',
            field=models.DateTimeField(blank=True, help_text='When the SLA clock was last paused. Null if not paused.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_policy',
            field=models.ForeignKey(blank=True, help_text='The SLA policy applied to this ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.slapolicy'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_resolution_due',
            field=models.DateTimeField(blank=True, help_text='UTC deadline for full resolution.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent status transition.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered the most recent status transition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('commented', 'Commented'), ('internal_note', 'Internal Note'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('escalated', 'Escalated'), ('escalated_manual', 'Manually Escalated'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed'), ('sla_paused', 'SLA Paused'), ('sla_resumed', 'SLA Resumed')], max_length=50),
        ),
    ]
