# Generated by Django 6.0.2 on 2026-04-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_phase3_resolution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='auto_close_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID of the pending auto-close task.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='csat_comment',
            field=models.TextField(blank=True, default='', help_text='Optional customer feedback text.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='csat_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Customer satisfaction rating (1-5).', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='csat_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the CSAT survey was submitted.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='needs_kb_article',
            field=models.BooleanField(default=False, help_text='Set by post-closure check if category lacks KB articles.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solved_at',
            field=models.DateTimeField(blank=True, help_text="When the ticket moved to 'resolved' status.", null=True),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('commented', 'Commented'), ('internal_note', 'Internal Note'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('escalated', 'Escalated'), ('escalated_manual', 'Manually Escalated'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed'), ('sla_paused', 'SLA Paused'), ('sla_resumed', 'SLA Resumed'), ('auto_closed', 'Auto-closed'), ('csat_received', 'CSAT Received')], max_length=50),
        ),
    ]
