# Generated by Django 6.0.2 on 2026-04-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_fix_resolved_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketactivity',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('commented', 'Commented'), ('internal_note', 'Internal Note'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('escalated', 'Escalated'), ('escalated_manual', 'Manually Escalated'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed'), ('sla_paused', 'SLA Paused'), ('sla_resumed', 'SLA Resumed'), ('auto_closed', 'Auto-closed'), ('csat_received', 'CSAT Received'), ('first_response', 'First Response Sent')], max_length=50),
        ),
    ]
