# Generated by Django 6.0.2 on 2026-04-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_add_first_response_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_extended_at',
            field=models.DateTimeField(blank=True, help_text='When an SLA deadline extension was last applied via escalation.', null=True),
        ),
    ]
