# Generated by Django 6.0.2 on 2026-04-02 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_add_sla_extended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pre_wait_status',
            field=models.ForeignKey(blank=True, help_text='Snapshot of the status before entering a pauses_sla status. Used to restore the previous status when leaving Waiting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.ticketstatus'),
        ),
    ]
