# Generated by Django 6.0.2 on 2026-04-02 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_auto_transition_on_assign'),
        ('tickets', '0017_add_pre_wait_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='If this ticket was merged, points to the primary ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='tickets.ticket'),
        ),
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(choices=[('duplicate_of', 'Duplicate of'), ('related_to', 'Related to'), ('blocks', 'Blocks'), ('blocked_by', 'Blocked by')], max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='tickets.ticket')),
                ('target_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='tickets.ticket')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ticket link',
                'verbose_name_plural': 'ticket links',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_ticket', models.F('target_ticket')), _negated=True), name='ticketlink_no_self_link')],
                'unique_together': {('source_ticket', 'target_ticket', 'link_type')},
            },
        ),
    ]
