# Generated by Django 6.0.2 on 2026-04-03 03:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_auto_transition_on_assign'),
        ('tickets', '0018_add_ticket_link_and_merged_into'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(help_text='Template body. Supports variables: {{ticket.number}}, {{ticket.subject}}, {{contact.name}}, {{agent.name}}, {{ticket.queue}}')),
                ('actions', models.JSONField(blank=True, default=list, help_text='List of actions, e.g. [{"action": "set_status", "value": "resolved"}, {"action": "set_priority", "value": "low"}, {"action": "add_tag", "value": "billing"}]')),
                ('is_shared', models.BooleanField(default=True, help_text='False = personal to creator only.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macros', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'macro',
                'verbose_name_plural': 'macros',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'is_shared'], name='tickets_mac_tenant__5a6ec8_idx')],
            },
        ),
    ]
