# Generated by Django 6.0.2 on 2026-04-05 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_add_contact_to_ticketactivity'),
        ('tenants', '0006_add_auto_transition_on_assign'),
        ('tickets', '0019_add_macro_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='account',
            field=models.ForeignKey(blank=True, help_text='CRM account associated with this ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='contacts.account'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deal_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monetary value of the deal (for deal-type tickets).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='expected_close_date',
            field=models.DateField(blank=True, help_text='Expected close date for deal-type tickets.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='follow_up_due_at',
            field=models.DateTimeField(blank=True, help_text='When a follow-up action is due for this ticket.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent CRM activity on this ticket.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='probability',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Win probability percentage (0-100) for deal-type tickets.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('support', 'Support'), ('deal', 'Deal'), ('inquiry', 'Inquiry')], default='support', help_text='Classifies the ticket as support, deal, or inquiry.', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact associated with the ticket at the time of this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('commented', 'Commented'), ('internal_note', 'Internal Note'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('escalated', 'Escalated'), ('escalated_manual', 'Manually Escalated'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed'), ('sla_paused', 'SLA Paused'), ('sla_resumed', 'SLA Resumed'), ('auto_closed', 'Auto-closed'), ('csat_received', 'CSAT Received'), ('first_response', 'First Response Sent'), ('pipeline_stage_changed', 'Pipeline Stage Changed')], max_length=50),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False, help_text='If True, new deal-type tickets default to this pipeline.')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'pipeline',
                'verbose_name_plural': 'pipelines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(help_text='Display order within the pipeline.')),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('probability', models.PositiveIntegerField(default=0, help_text='Default win probability percentage (0-100) for this stage.')),
                ('is_won', models.BooleanField(default=False, help_text='If True, reaching this stage marks the deal as won.')),
                ('is_lost', models.BooleanField(default=False, help_text='If True, reaching this stage marks the deal as lost.')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tickets.pipeline')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'pipeline stage',
                'verbose_name_plural': 'pipeline stages',
                'ordering': ['order'],
                'unique_together': {('pipeline', 'order')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='pipeline_stage',
            field=models.ForeignKey(blank=True, help_text='Current pipeline stage (for deal-type tickets).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.pipelinestage'),
        ),
    ]
