# Generated by Django 6.0.2 on 2026-04-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_backfill_ticketactivity_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='lost_at',
            field=models.DateTimeField(blank=True, help_text='When the deal was marked as lost.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='lost_reason',
            field=models.CharField(blank=True, help_text='Reason the deal was lost.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='won_at',
            field=models.DateTimeField(blank=True, help_text='When the deal was marked as won.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='won_reason',
            field=models.CharField(blank=True, help_text='Reason the deal was won.', max_length=500, null=True),
        ),
    ]
