# Generated by Django 6.0.2 on 2026-04-09 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_auto_transition_on_assign'),
        ('tickets', '0023_add_inbox_workflow_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this ticket was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft-deleted this ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-deleted tickets are hidden from lists but retained for audit.'),
        ),
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', help_text='Brief description shown in the template picker.', max_length=500)),
                ('subject_template', models.CharField(blank=True, default='', help_text='Pre-filled subject line.', max_length=255)),
                ('body_template', models.TextField(blank=True, default='', help_text='Pre-filled description/body content.')),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('default_category', models.CharField(blank=True, default='', max_length=100)),
                ('default_tags', models.JSONField(blank=True, default=list)),
                ('default_ticket_type', models.CharField(choices=[('support', 'Support'), ('deal', 'Deal'), ('inquiry', 'Inquiry')], default='support', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_templates', to=settings.AUTH_USER_MODEL)),
                ('default_queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='tickets.queue')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ticket template',
                'verbose_name_plural': 'ticket templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='tickets_tic_tenant__9e9149_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketWatcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('manual', 'Manually added'), ('mentioned', 'Mentioned in comment'), ('commented', 'Posted a comment'), ('cc', "CC'd on email")], default='manual', max_length=20)),
                ('is_muted', models.BooleanField(default=False, help_text="If True, the user won't receive notifications for this ticket.")),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket watcher',
                'verbose_name_plural': 'ticket watchers',
                'ordering': ['-created_at'],
                'unique_together': {('ticket', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Time spent in minutes.')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the work started (for timer-based entries).', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the work ended (for timer-based entries).', null=True)),
                ('description', models.TextField(blank=True, default='', help_text='What was done during this time.')),
                ('is_billable', models.BooleanField(default=False, help_text='Whether this time entry is billable to the customer.')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'time entry',
                'verbose_name_plural': 'time entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='tickets_tim_ticket__3c3481_idx'), models.Index(fields=['user', 'created_at'], name='tickets_tim_user_id_458fc4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='The URL to receive POST webhook payloads.', max_length=2000)),
                ('secret', models.CharField(blank=True, default='', help_text='HMAC secret for payload signature verification.', max_length=255)),
                ('events', models.JSONField(default=list, help_text='List of event types to subscribe to.')),
                ('is_active', models.BooleanField(default=True)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Additional HTTP headers to include in requests.')),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Consecutive delivery failure count. Auto-disabled at 10.')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'webhook',
                'verbose_name_plural': 'webhooks',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='tickets_web_tenant__b36000_idx')],
            },
        ),
    ]
