# Generated by Django 6.0.2 on 2026-05-25 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox_hub', '0001_initial'),
        ('tickets', '0026_alter_ticketactivity_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='inbox_hub.department'),
        ),
    ]
