# Generated by Django 6.0.2 on 2026-05-25 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0005_widen_phone_field'),
        ('inbound_email', '0008_alter_inboundemail_recipient_email_imappollstate'),
        ('tenants', '0008_tenantsettings_auto_assign_inbound_email_tickets'),
        ('tickets', '0026_alter_ticketactivity_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('business_hours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.businesshours')),
                ('default_queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_departments', to='tickets.queue')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_departments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='inbox_hub.department')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='departments', through='inbox_hub.DepartmentMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HubEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_agent', 'Pending Agent'), ('awaiting_customer', 'Awaiting Customer'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('converted_to_ticket', 'Converted to Ticket'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('sla_response_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sla_resolution_due_at', models.DateTimeField(blank=True, null=True)),
                ('response_breached', models.BooleanField(default=False)),
                ('resolution_breached', models.BooleanField(default=False)),
                ('first_responded_at', models.DateTimeField(blank=True, null=True)),
                ('first_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('pause_started_at', models.DateTimeField(blank=True, null=True)),
                ('total_pause_seconds', models.PositiveIntegerField(default=0)),
                ('escalation_count', models.PositiveIntegerField(default=0)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissal_reason', models.CharField(blank=True, max_length=255)),
                ('auto_classification_data', models.JSONField(blank=True, default=dict)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hub_emails', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_emails', to='contacts.contact')),
                ('converted_ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_hub_email', to='tickets.ticket')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_emails', to='inbox_hub.department')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inbound', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hub_email', to='inbound_email.inboundemail')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_emails', to='tickets.queue')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HubEmailAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('escalation', 'Escalation'), ('reassignment', 'Reassignment')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hub_email_assignments', to=settings.AUTH_USER_MODEL)),
                ('hub_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inbox_hub.hubemail')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HubEmailNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hub_email_notes', to=settings.AUTH_USER_MODEL)),
                ('hub_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inbox_hub.hubemail')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HubEmailSLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10)),
                ('response_minutes', models.PositiveIntegerField()),
                ('resolution_minutes', models.PositiveIntegerField()),
                ('escalation_minutes', models.PositiveIntegerField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_email_slas', to='inbox_hub.department')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_email_slas', to='tickets.queue')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='QueueRouting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy_code', models.CharField(default='availability_aware|least_loaded|round_robin', max_length=80)),
                ('leave_unassigned_when_no_match', models.BooleanField(default=True)),
                ('queue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hub_routing', to='tickets.queue')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(db_index=True, default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('match', models.JSONField(default=dict)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10, null=True)),
                ('stop_on_match', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='inbox_hub.department')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='tickets.queue')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='departmentmembership',
            constraint=models.UniqueConstraint(fields=('department', 'user'), name='ih_deptmember_dept_user_uniq'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'is_active'], name='ih_dept_tenant_active'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='ih_department_tenant_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='hubemail',
            index=models.Index(fields=['tenant', 'state', '-created_at'], name='ih_email_t_state_created'),
        ),
        migrations.AddIndex(
            model_name='hubemail',
            index=models.Index(fields=['tenant', 'queue', 'state'], name='ih_email_t_queue_state'),
        ),
        migrations.AddIndex(
            model_name='hubemail',
            index=models.Index(fields=['tenant', 'assignee', 'state'], name='ih_email_t_assignee_state'),
        ),
        migrations.AddIndex(
            model_name='hubemail',
            index=models.Index(fields=['tenant', 'department', 'state'], name='ih_email_t_dept_state'),
        ),
        migrations.AddIndex(
            model_name='hubemail',
            index=models.Index(condition=models.Q(('state__in', ['new', 'assigned', 'in_progress', 'pending_agent'])), fields=['tenant', 'sla_response_due_at'], name='ih_email_active_sla_due'),
        ),
        migrations.AddIndex(
            model_name='hubemailassignment',
            index=models.Index(fields=['hub_email', '-created_at'], name='ih_assign_email_created'),
        ),
        migrations.AddConstraint(
            model_name='hubemailsla',
            constraint=models.UniqueConstraint(condition=models.Q(('queue__isnull', False)), fields=('queue', 'priority'), name='ih_sla_queue_priority_uniq'),
        ),
        migrations.AddConstraint(
            model_name='hubemailsla',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('department', 'priority'), name='ih_sla_dept_priority_uniq'),
        ),
        migrations.AddIndex(
            model_name='routingrule',
            index=models.Index(fields=['tenant', 'is_active', 'order'], name='ih_rule_active_order'),
        ),
    ]
