# Generated by Django 6.0.2 on 2026-07-02 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_widen_phone_field'),
        ('inbound_email', '0010_inboundemail_assignee_and_more'),
        ('inbox_hub', '0001_initial'),
        ('tenants', '0011_auto_send_ticket_created_email_default_false'),
        ('tickets', '0027_queue_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hubemail',
            name='ih_email_active_sla_due',
        ),
        migrations.AddIndex(
            model_name='hubemail',
            index=models.Index(condition=models.Q(('state__in', ['new', 'assigned', 'in_progress', 'pending_agent', 'escalated'])), fields=['tenant', 'sla_response_due_at'], name='ih_email_active_sla_due'),
        ),
    ]
