# Generated by Django 6.0.2 on 2026-02-06 04:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('max_concurrent_tickets', models.PositiveIntegerField(default=10, help_text='Maximum number of tickets this agent can handle concurrently.')),
                ('current_ticket_count', models.PositiveIntegerField(default=0, help_text='Current number of open tickets assigned to this agent.')),
                ('last_activity', models.DateTimeField(blank=True, help_text="Timestamp of the agent's most recent activity.", null=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agent availability',
                'verbose_name_plural': 'agent availabilities',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
