# Generated by Django 6.0.2 on 2026-02-19 02:48

from django.db import migrations, models


def convert_away_busy_to_offline(apps, schema_editor):
    AgentAvailability = apps.get_model('agents', 'AgentAvailability')
    AgentAvailability.objects.filter(status__in=['away', 'busy']).update(status='offline')


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_away_busy_to_offline, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='agentavailability',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
