# Generated by Django 6.0.2 on 2026-03-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_remove_away_busy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentavailability',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
