# Generated by Django 6.0.2 on 2026-03-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_add_away_busy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentavailability',
            name='status_message',
            field=models.CharField(blank=True, help_text="Custom status message (e.g. 'In a meeting').", max_length=100, null=True),
        ),
    ]
