# Generated by Django 6.0.2 on 2026-03-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_add_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentavailability',
            name='auto_away_outside_hours',
            field=models.BooleanField(default=False, help_text='Automatically set status to away outside working hours.'),
        ),
        migrations.AddField(
            model_name='agentavailability',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text="Per-day working hours, e.g. {'mon': {'enabled': true, 'start': '09:00', 'end': '17:00'}, ...}"),
        ),
    ]
