# Generated by Django 6.0.2 on 2026-05-11 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentavailability_auto_away_outside_hours_and_more'),
        ('tenants', '0008_tenantsettings_auto_assign_inbound_email_tickets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAgentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Stable identifier used by the API and dropdown.', max_length=40)),
                ('label', models.CharField(help_text="Display name shown in the dropdown (e.g. 'In Meeting').", max_length=50)),
                ('description', models.CharField(blank=True, default='', help_text='Short helper text shown under the label.', max_length=100)),
                ('color', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink'), ('gray', 'Gray')], default='blue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_agent_statuses_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'custom agent status',
                'verbose_name_plural': 'custom agent statuses',
                'ordering': ['order', 'label'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='agentavailability',
            name='custom_status',
            field=models.ForeignKey(blank=True, help_text='When set, takes precedence over the built-in status for display purposes. Cleared when the agent picks a built-in status.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='agents.customagentstatus'),
        ),
    ]
