# Generated by Django 6.0.2 on 2026-06-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_customagentstatus_agentavailability_custom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentavailability',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last presence heartbeat from a live /ws/live/ socket. Re-stamped on connect and on each heartbeat ping; aged out by the presence reaper. Drives the freshness half of is_assignable.', null=True),
        ),
    ]
