# Generated by Django 6.0.2 on 2026-04-05 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_lead_score'),
        ('crm', '0001_initial'),
        ('tenants', '0006_add_auto_transition_on_assign'),
        ('tickets', '0023_add_inbox_workflow_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='When this outbound recall is due.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recalls_assigned', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recalls', to='contacts.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recalls_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recalls', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'recall',
                'verbose_name_plural': 'recalls',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['tenant', 'scheduled_at', 'completed_at', 'cancelled_at'], name='recall_overdue_idx'), models.Index(fields=['tenant', 'assigned_to'], name='crm_recall_tenant__4902e6_idx'), models.Index(fields=['tenant', 'contact'], name='crm_recall_tenant__de5c8b_idx')],
            },
        ),
    ]
