# Generated by Django 6.0.2 on 2026-06-11 07:36

from django.db import migrations, models
from django.db.models import F
from django.utils import timezone


def suppress_existing_due_reminders(apps, schema_editor):
    """
    Backfill ``due_notified_at`` for reminders that are ALREADY past due at
    migration time so the new ``fire_due_reminders`` task does not fire a
    popup for the entire historical backlog on its first beat tick.

    Setting ``due_notified_at = scheduled_at`` marks them "already notified at
    their due time": the task's re-arm guard (fire while
    ``due_notified_at < scheduled_at``) treats equal-or-greater as handled, so
    these stay quiet — yet any future reschedule still re-arms correctly.
    Only past, still-active (not completed/cancelled) reminders are touched;
    future reminders keep ``due_notified_at = NULL`` and fire normally when due.
    """
    Reminder = apps.get_model("crm", "Reminder")
    Reminder.objects.filter(
        scheduled_at__lte=timezone.now(),
        completed_at__isnull=True,
        cancelled_at__isnull=True,
        due_notified_at__isnull=True,
    ).update(due_notified_at=F("scheduled_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_reminder_m2m_contacts_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='due_notified_at',
            field=models.DateTimeField(blank=True, help_text="When the one-shot 'reminder due' alert was sent. Prevents the fire_due_reminders task from re-notifying every beat tick. Automatically re-arms whenever scheduled_at moves forward (the task re-fires while due_notified_at < scheduled_at).", null=True),
        ),
        migrations.RunPython(
            suppress_existing_due_reminders,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
