# Generated by Django 6.0.2 on 2026-02-06 04:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('counter', 'Counter'), ('chart_bar', 'Bar Chart'), ('chart_line', 'Line Chart'), ('chart_pie', 'Pie Chart'), ('table', 'Table')], max_length=20)),
                ('data_source', models.CharField(help_text='Reference to the data provider (e.g. "tickets.open_count").', max_length=100)),
                ('filters', models.JSONField(blank=True, default=dict, help_text="Optional filter criteria applied to this widget's data.")),
                ('position', models.JSONField(blank=True, default=dict, help_text='Grid position and size (e.g. {"x": 0, "y": 0, "w": 6, "h": 4}).')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='If set, this widget is personal to this user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dashboard widget',
                'verbose_name_plural': 'dashboard widgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('ticket_volume', 'Ticket Volume'), ('sla_compliance', 'SLA Compliance'), ('agent_performance', 'Agent Performance'), ('contact_growth', 'Contact Growth'), ('ticket_by_priority', 'Ticket by Priority'), ('ticket_by_status', 'Ticket by Status'), ('response_time', 'Response Time')], max_length=50)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Stored filter criteria for this report (e.g. date range, priority).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_definitions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'report definition',
                'verbose_name_plural': 'report definitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('pdf', 'PDF')], max_length=20)),
                ('resource_type', models.CharField(help_text='The type of resource being exported (e.g. "tickets", "contacts").', max_length=50)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filter criteria for the exported data.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Generated export file.', null=True, upload_to='exports/')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if the export failed.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('report', models.ForeignKey(blank=True, help_text='Optional report definition this export is based on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to='analytics.reportdefinition')),
            ],
            options={
                'verbose_name': 'export job',
                'verbose_name_plural': 'export jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
