# Generated by Django 6.0.2 on 2026-03-18 03:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenantsettings_inbound_email_address'),
        ('tickets', '0008_rename_tickets_can_tenant__83e6de_idx_tickets_can_tenant__e45d2f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(db_index=True, help_text='RFC 2822 Message-ID header for dedup.', max_length=512)),
                ('in_reply_to', models.CharField(blank=True, default='', help_text='In-Reply-To header for threading.', max_length=512)),
                ('references', models.TextField(blank=True, default='', help_text='References header (space-separated Message-IDs).')),
                ('sender_email', models.EmailField(db_index=True, max_length=254)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_email', models.EmailField(help_text='The address this email was sent to (e.g. support@tenant.kanzan.io).', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('raw_headers', models.TextField(blank=True, default='', help_text='Full raw headers for debugging.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ticket_created', 'Ticket Created'), ('reply_added', 'Reply Added'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if processing failed.')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_emails', to='tenants.tenant')),
                ('ticket', models.ForeignKey(blank=True, help_text='The ticket this email created or was threaded to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='inbound_ema_tenant__44d469_idx'), models.Index(fields=['message_id'], name='inbound_ema_message_00bbba_idx')],
            },
        ),
    ]
