# Generated by Django 6.0.2 on 2026-03-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='attachment_metadata',
            field=models.JSONField(blank=True, default=list, help_text='List of dicts describing attachments received with this email. Each entry: {filename, content_type, size, storage_path}.'),
        ),
    ]
