# Generated by Django 6.0.2 on 2026-03-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_email', '0002_inboundemail_attachment_metadata'),
        ('tenants', '0004_tenantsettings_inbound_email_address'),
        ('tickets', '0008_rename_tickets_can_tenant__83e6de_idx_tickets_can_tenant__e45d2f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, default='inbound', help_text='Whether this record represents an email received (inbound) or sent (outbound). Outbound records exist for Message-ID threading so customer replies can be matched back.', max_length=10),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text="Unique key for deduplication. Format: 'in:{tenant_id}:{message_id}' for inbound, 'out:{tenant_id}:{ticket_id}:{message_id}' for outbound.", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('system', 'System'), ('agent', 'Agent')], default='customer', help_text='Who sent this email: customer (inbound from external), system (automated notification), or agent (manual send from UI).', max_length=10),
        ),
        migrations.AlterField(
            model_name='inboundemail',
            name='in_reply_to',
            field=models.CharField(blank=True, default='', help_text='In-Reply-To header for threading. Stored WITHOUT angle brackets.', max_length=512),
        ),
        migrations.AlterField(
            model_name='inboundemail',
            name='message_id',
            field=models.CharField(db_index=True, help_text='RFC 2822 Message-ID header. Stored WITHOUT angle brackets.', max_length=512),
        ),
        migrations.AlterField(
            model_name='inboundemail',
            name='references',
            field=models.TextField(blank=True, default='', help_text='References header (space-separated Message-IDs). Each ID stored WITHOUT angle brackets.'),
        ),
        migrations.AlterField(
            model_name='inboundemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ticket_created', 'Ticket Created'), ('reply_added', 'Reply Added'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['tenant', 'direction', 'status'], name='email_tenant_dir_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['ticket', 'direction'], name='email_ticket_direction_idx'),
        ),
    ]
