# Generated by Django 6.0.2 on 2026-04-02 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_email', '0004_backfill_direction_and_idempotency'),
        ('tenants', '0006_add_auto_transition_on_assign'),
        ('tickets', '0017_add_pre_wait_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ticket_created', 'Ticket Created'), ('reply_added', 'Reply Added'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('bounced', 'Bounced'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BounceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_address', models.EmailField(help_text='Original sender of the bounced message (the mailer-daemon).', max_length=254)),
                ('to_address', models.EmailField(blank=True, default='', help_text='The intended recipient whose delivery failed.', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('bounce_reason', models.TextField(blank=True, default='', help_text='Header-derived reason for the bounce (e.g. filter name, header value).')),
                ('inbound_email', models.ForeignKey(help_text='The InboundEmail record that contained the bounce.', on_delete=django.db.models.deletion.CASCADE, related_name='bounce_logs', to='inbound_email.inboundemail')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bounce_logs', to='tenants.tenant')),
                ('ticket', models.ForeignKey(blank=True, help_text='The ticket this bounce relates to, if threading matched.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounce_logs', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'bounce log',
                'verbose_name_plural': 'bounce logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
