# Generated by Django 6.0.2 on 2026-04-05 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_email', '0005_add_bounced_status_and_bouncelog'),
        ('tenants', '0006_add_auto_transition_on_assign'),
        ('tickets', '0023_add_inbox_workflow_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='action_taken',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('assign', 'Assign'), ('close', 'Close')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='actioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='inbox_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('linked', 'Linked'), ('actioned', 'Actioned'), ('ignored', 'Ignored')], db_index=True, default='pending', help_text='Agent inbox workflow state.', max_length=20),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='linked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='linked_ticket',
            field=models.ForeignKey(blank=True, help_text='Ticket manually linked by an agent via the inbox workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_inbound_emails', to='tickets.ticket'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['tenant', 'inbox_status'], name='email_tenant_inbox_status_idx'),
        ),
    ]
