# Generated by Django 6.0.2 on 2026-04-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_email', '0006_add_inbox_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
