# Generated by Django 6.0.2 on 2026-04-23 05:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_email', '0007_inboundemail_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundemail',
            name='recipient_email',
            field=models.EmailField(help_text='The address this email was sent to (e.g. support@tenant.kanzen.io).', max_length=254),
        ),
        migrations.CreateModel(
            name='IMAPPollState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('mailbox', models.CharField(default='INBOX', max_length=255)),
                ('uid_validity', models.BigIntegerField(default=0)),
                ('last_uid', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'IMAP poll state',
                'verbose_name_plural': 'IMAP poll state',
                'unique_together': {('host', 'user', 'mailbox')},
            },
        ),
    ]
