# Generated by Django 6.0.2 on 2026-05-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_email', '0008_alter_inboundemail_recipient_email_imappollstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ticket_created', 'Ticket Created'), ('reply_added', 'Reply Added'), ('parked_in_hub', 'Parked in Hub'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('bounced', 'Bounced'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
