# Generated by Django 6.0.2 on 2026-06-08 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_email', '0009_alter_inboundemail_status'),
        ('tenants', '0010_tenantsettings_inbox_hub_auto_assign_and_more'),
        ('tickets', '0027_queue_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text="Agent this email was handed to (e.g. assigned from the Inbox Hub). Surfaces the original message in that agent's email inbox.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inbound_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['tenant', 'assignee', 'inbox_status'], name='email_tenant_assignee_idx'),
        ),
    ]
