# Generated by Django 6.0.2 on 2026-02-06 04:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('ticket', 'Ticket'), ('deal', 'Deal')], help_text='The type of entity this board tracks.', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default board for its resource type.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boards', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'board',
                'verbose_name_plural': 'boards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(help_text='Display order of the column within the board.')),
                ('wip_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of cards allowed in this column. 0 or null means no limit.', null=True)),
                ('color', models.CharField(blank=True, help_text="Hex colour code for the column header (e.g. '#ff6600').", max_length=7, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='kanban.board')),
                ('status', models.ForeignKey(blank=True, help_text='Optional mapping to a ticket status.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_columns', to='tickets.ticketstatus')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'column',
                'verbose_name_plural': 'columns',
                'ordering': ['order'],
                'unique_together': {('board', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CardPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Position of this card within its column.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.column')),
            ],
            options={
                'verbose_name': 'card position',
                'verbose_name_plural': 'card positions',
                'ordering': ['order'],
                'unique_together': {('column', 'content_type', 'object_id')},
            },
        ),
    ]
