# Generated by Django 6.0.2 on 2026-03-23 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_add_tenant_to_cardposition'),
        ('tenants', '0004_tenantsettings_inbound_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardposition',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
    ]
