# Generated by Django 6.0.2 on 2026-04-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('ticket_updated', 'Ticket Updated'), ('ticket_comment', 'Ticket Comment'), ('mention', 'Mention'), ('message', 'Message'), ('sla_breach', 'SLA Breach'), ('ticket_overdue', 'Ticket Overdue'), ('payment_failed', 'Payment Failed'), ('subscription_change', 'Subscription Change'), ('invitation', 'Invitation'), ('agent_status_change', 'Agent Status Change'), ('ticket_followup_overdue', 'Ticket Follow-up Overdue'), ('reminder_overdue', 'Reminder Overdue'), ('kb_review_requested', 'KB Review Requested'), ('kb_article_reviewed', 'KB Article Reviewed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('ticket_updated', 'Ticket Updated'), ('ticket_comment', 'Ticket Comment'), ('mention', 'Mention'), ('message', 'Message'), ('sla_breach', 'SLA Breach'), ('ticket_overdue', 'Ticket Overdue'), ('payment_failed', 'Payment Failed'), ('subscription_change', 'Subscription Change'), ('invitation', 'Invitation'), ('agent_status_change', 'Agent Status Change'), ('ticket_followup_overdue', 'Ticket Follow-up Overdue'), ('reminder_overdue', 'Reminder Overdue'), ('kb_review_requested', 'KB Review Requested'), ('kb_article_reviewed', 'KB Article Reviewed')], max_length=50),
        ),
    ]
