# Generated by Django 6.0.2 on 2026-06-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('ticket_updated', 'Ticket Updated'), ('ticket_comment', 'Ticket Comment'), ('mention', 'Mention'), ('message', 'Message'), ('sla_breach', 'SLA Breach'), ('ticket_overdue', 'Ticket Overdue'), ('payment_failed', 'Payment Failed'), ('subscription_change', 'Subscription Change'), ('invitation', 'Invitation'), ('agent_status_change', 'Agent Status Change'), ('ticket_followup_overdue', 'Ticket Follow-up Overdue'), ('reminder_due', 'Reminder Due'), ('reminder_overdue', 'Reminder Overdue'), ('kb_review_requested', 'KB Review Requested'), ('kb_article_reviewed', 'KB Article Reviewed'), ('hub_email_assigned', 'Hub Email Assigned'), ('hub_email_reassigned', 'Hub Email Reassigned'), ('hub_email_escalated_to_me', 'Hub Email Escalated to Me'), ('hub_email_sla_breach_warning', 'Hub Email SLA Breach Warning'), ('hub_email_sla_breached', 'Hub Email SLA Breached')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('ticket_updated', 'Ticket Updated'), ('ticket_comment', 'Ticket Comment'), ('mention', 'Mention'), ('message', 'Message'), ('sla_breach', 'SLA Breach'), ('ticket_overdue', 'Ticket Overdue'), ('payment_failed', 'Payment Failed'), ('subscription_change', 'Subscription Change'), ('invitation', 'Invitation'), ('agent_status_change', 'Agent Status Change'), ('ticket_followup_overdue', 'Ticket Follow-up Overdue'), ('reminder_due', 'Reminder Due'), ('reminder_overdue', 'Reminder Overdue'), ('kb_review_requested', 'KB Review Requested'), ('kb_article_reviewed', 'KB Article Reviewed'), ('hub_email_assigned', 'Hub Email Assigned'), ('hub_email_reassigned', 'Hub Email Reassigned'), ('hub_email_escalated_to_me', 'Hub Email Escalated to Me'), ('hub_email_sla_breach_warning', 'Hub Email SLA Breach Warning'), ('hub_email_sla_breached', 'Hub Email SLA Breached')], max_length=50),
        ),
    ]
